version: '3.3'

volumes:
  mongodb_data:
  mysql_data:

services:
  wang-server:
    image: wang-server
    container_name: wang-server
    ports:
      - "3001:3001"
    restart: always

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - 'mysql_data:/Users/Shared/mysql'
    ports:
      - "3306:3306"
