version: '3.3'

services:
  wang-server:
    image: wang-server
    container_name: wang-serveo
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: wang_db
      DB_USERNAME: root
      DB_PASSWORD: root@ncu 
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    restart: always

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root@ncu
      MYSQL_DATABASE: wang_db
      MYSQL_USER: aseven
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/bitnami/mysql
volumes:
  mysql-data:
